### ISSUE TITLE
Shading of 3D coati

### ISSUE THREAD

**Issue by Skillmon** [samcarter/tikzlings#11]
The shading of the 3D coati's face, more specifically it's nose and the surroundings, look weird. It looks like the nose casts its shadow to the left, but the light's supposed to come from the left. So the shadings around the nose should be mirrored.

**Comment by samcarter** [comment]
Changed the shading

![coati](https://user-images.githubusercontent.com/43832342/73069572-4faa1680-3eae-11ea-92f7-3b1f3741eb9b.png)

**Comment by samcarter** [comment]
Tanks for the report!
