### ISSUE TITLE
A coati with a right sideward

### ISSUE THREAD

**Issue by tremulotmaths** [samcarter/tikzlings#12]
Good evening,
I'd like to create a coati with a right sideward.
A teacher from Orleans (France) used your package and has found how to create what I'm looking for, as you can see in the attached document.
But I haven't managed to create the same coati.
Have your already done it or could you help me if it's not too time-consuming?
Thanks in advance for your answer.
![coati](https://user-images.githubusercontent.com/49996583/74614113-72c68f80-5115-11ea-88e6-c9f45c81250e.png)

**Comment by samcarter** [comment]
Thanks for your interests in the coati!

You can use a little tikz trick to make it look in the other direction, `xscale=-1`:

```
\documentclass{standalone}
\usepackage{tikzlings}

\begin{document}
	
\begin{tikzpicture}
	\coati[sideward,xscale=-1]
\end{tikzpicture}	
	
\end{document}
```

**Comment by tremulotmaths** [comment]
Thank you very much for your quick answer.
Just after switching off my computer...I thought about a scalebox{-1}[1] which is the same as your solution.
Sorry for my silly question.
Anyway, thank very much for your so nice package!!
Best regards

**Comment by samcarter** [comment]
@tremulotmaths  You're welcome! (although I have to disagree with you calling this question silly :) )
