### ISSUE TITLE
Eye does not appear with black dark body

### ISSUE THREAD

**Issue by seloumi** [samcarter/tikzlings#17]
If we use `body=black` with \bear eye  does not appear, here an example 

```latex
\documentclass[border=5mm]{standalone}
\usepackage{tikzlings}

\begin{document}

\begin{tikzpicture}
\bear[body=black,scale=5]
\end{tikzpicture}

\end{document}

```

![image](https://user-images.githubusercontent.com/8249073/101262063-1aac5880-373c-11eb-8005-3d0a1599a49a.png)

**Comment by samcarter** [comment]
Well, they eyes do appear, they are just also black. However I can add an option to change the colour of the eyes.

**Comment by samcarter** [comment]
Try now  with 
```
\documentclass[border=5mm]{standalone}
\usepackage{tikzlings}

\begin{document}

\begin{tikzpicture}
\bear[body=black,scale=5,eye=red]
\end{tikzpicture}

\end{document}
```
![document](https://user-images.githubusercontent.com/43832342/101262573-2732b000-3740-11eb-81fe-d6e5ccb58976.png)

**Comment by seloumi** [comment]
Thanks, the issue eppear also with black `\marmot`

**Comment by samcarter** [comment]
All TikZlings can now change their eye colour
