### ISSUE TITLE
Add humans

### ISSUE THREAD

**Issue by TejasAvinashShetty** [samcarter/tikzlings#24]
Good starting points
[tikzpeople](https://www.ctan.org/pkg/tikzpeople)
[human question](https://tex.stackexchange.com/q/84275/129388), especially this 
[stickman](https://tex.stackexchange.com/a/487863/129388)

**Comment by samcarter** [comment]
I'm going to decline this feature request. I don't think I could compete with such great packages like tikzpeople or your upcoming package :)
