### ISSUE TITLE
problems with Overleaf

### ISSUE THREAD

**Issue by Joanjoan2017** [samcarter/tikzlings#25]
Dear Sirs,
I use Overleaf within my educational project titled LaTeX-2018-edu to teach LaTeX instead of teaching Word.
I have started testing the packages in the document 
“The TikZlings package drawing animals and beings in TikZ”
samcarter
https://github.com/samcarter/tikzlings
https://www.ctan.org/pkg/tikzlings
Version v0.8 – 2021/08/06
and it gives a lot of execution problems with Overleaf.

For example: compiling with 
\usepackage{tikzlings-bat} gives compilation error;
with the bear package using the following instructions
\tikz\bearwear % default
[long sleeves,
round neckline];
\tikz\bearwear
[t-shirt];
\tikz\bearwear
[muscle shirt];
do not draw the costumes and give 3 errors; in the same package he does not draw red eyes; with all packages the instruction [contour = black] gives error.
I would be very grateful that you solve these problems.
MWE
```
\documentclass[a4paper,11pt]{article}
\usepackage[utf8x]{inputenc} %per posar caràcters no ASCII
\usepackage[catalan]{babel} %idioma de treball

\usepackage[tmargin=2cm,bmargin=2cm,lmargin=2cm,rmargin=2cm]{geometry} %defineix els marges de treball

\usepackage{parskip}
\setlength{\parindent}{0mm}
\usepackage[T1]{fontenc}
\usepackage{graphicx,wrapfig}

\usepackage[dvipsnames]{xcolor}

\usepackage{tikz}
\usepackage{tikzlings}

\usepackage{tikzlings-anteaters}
%\usepackage{tikzlings-bats} % doesn't work
\usepackage{tikzlings-bears}
\usepackage{tikzlings-bees}
\usepackage{tikzlings-mice}
\usepackage{tikzlings-marmots}



\begin{document}

\begin{tikzpicture}
%\anteater[eye=red]  % aquest no funciona
%\bearwear[t-shirt]
\end{tikzpicture}

\tikz\bearwear % default
[long sleeves,
round neckline];  %gives error
\tikz\bearwear
[t-shirt];    %gives error
\tikz\bearwear
[muscle shirt];  %gives error

\begin{tikzpicture}
\bee[contour=black]    %gives error don't recognize the word contour
\end{tikzpicture}

\end{document}
```

**Comment by samcarter** [comment]
After adding `\usepackage{bearwear}` your MWE compiles for me. Can  you test the following code on overleaf? If it does not work, please show your .log file.

```
\documentclass[a4paper,11pt]{article}
\usepackage[utf8x]{inputenc} %per posar caràcters no ASCII
\usepackage[catalan]{babel} %idioma de treball

\usepackage[tmargin=2cm,bmargin=2cm,lmargin=2cm,rmargin=2cm]{geometry} %defineix els marges de treball

\usepackage{parskip}
\setlength{\parindent}{0mm}
\usepackage[T1]{fontenc}
\usepackage{graphicx,wrapfig}

\usepackage[dvipsnames]{xcolor}

\usepackage{tikz}
\usepackage{tikzlings}
\usepackage{bearwear}
%\usepackage{tikzlings-anteaters}
%\usepackage{tikzlings-bats} % doesn't work
%\usepackage{tikzlings-bears}
%\usepackage{tikzlings-bees}
%\usepackage{tikzlings-mice}
%\usepackage{tikzlings-marmots}



\begin{document}

\begin{tikzpicture}
\anteater[eye=red]  % aquest no funciona
\bearwear[t-shirt]
\end{tikzpicture}

\tikz\bearwear % default
[long sleeves,
round neckline];  %gives error
\tikz\bearwear
[t-shirt];    %gives error
\tikz\bearwear
[muscle shirt];  %gives error

\begin{tikzpicture}
\bee[contour=black]    %gives error don't recognize the word contour
\end{tikzpicture}

\end{document}
```

**Comment by Joanjoan2017** [comment]
Dear Sirs,
I have attached two screenshots. One is using the
\usepackage[tikzlings-bats]  screenshot (bats_package.png), the other is
using both \usepackage{tikzlings-bears} and \usepackage{bearwear}
screenshot (contour.png).

As you can see using the bats package it gives a compilation error. I have
underlined the error message in blue: "The compiler cannot find the file
you want to include".

Using,
\usepackage [bearwear], the first two instructions
\begin{tikzpicture}

\anteater[eye = red]  % this does not work

\bearwear[t-shirt]

\end{tikzpicture}

the following is displayed:
the anteater is put on a t-shirt but does not have red eyes. Interestingly,
the
\usepackage{tikzlings-anteaters}  is not installed but the anteater appears.

The following instructions
\tikz\bearwear % default
[long sleeves,
round neckline];  %gives error

\tikz\bearwear
[t-shirt];    %gives error

\tikz\bearwear
[muscle shirt];  %gives error

do not work
Activating the \usepackage{tikzlings-bears} do not work either.

The last error is using the contour statement. This error is repeated in
all drawings. In this case I used bear, as is shown
\begin{tikzpicture}

\bear[contour=black]    %gives error don't recognize the word contour

\end{tikzpicture}

I would be very grateful that you try to solve these problems. Also, please
translate the bear problems to Dr. Ulrike Fischer because she develops the
bearwear package.

Thanking you in advance and looking forward to hearing from you,

Sincerely yours
Dr. Joan Verdaguer-Codina



Missatge de samcarter ***@***.***> del dia dv., 5 de nov.
2021 a les 22:57:

**Comment by samcarter** [comment]
I can't see any screenshots, but please show your .log file so I can see which package version overleaf uses. The bats need version 0.8

**Comment by Joanjoan2017** [comment]
I will write to Overleaf notifying this issue to fix.

Thank you so much for your help.

Sincerely yours
Dr. Joan Verdaguer-Codina

Missatge de samcarter ***@***.***> del dia dg., 7 de nov.
2021 a les 14:13:

**Comment by Joanjoan2017** [comment]
I forgot to attach a little better screenshots.
Thanks again

Missatge de iesmyp_tecno iesmyp_tecno ***@***.***> del dia dg., 7
de nov. 2021 a les 14:17:

**Comment by samcarter** [comment]
Sorry, but I can't see any screenshots
