### ISSUE TITLE
Wolf Addition

### ISSUE THREAD

**Issue by cfroccajr** [samcarter/tikzlings#26]
My university just adopted a new mascot so I created a wolfling.  Would you like the code?
[wolf_test.pdf](https://github.com/samcarter/tikzlings/files/8524841/wolf_test.pdf)

**Comment by samcarter** [comment]
Oh, nice!

I'd love to add the wolf to the package!

**Comment by cfroccajr** [comment]
Okay, lets' see if this works:
https://github.com/cfroccajr/wolfling.git

**Comment by samcarter** [comment]
Thanks a lot! That is great!

Can I use your github user name when crediting you in the documentation or would you prefer some other name?

And very important: each of the tikzlings has a name in the documentation. Would you like to choose a name for the wolf?

**Comment by cfroccajr** [comment]
The github user name would be good, I use it for some other projects already.
How about Westy for the name since I am at Western CT State University.

**Comment by samcarter** [comment]
That's a cute name! Perfect!

**Comment by samcarter** [comment]
I just added the wolf to the tikzlings version on github (with some tiny modifications, like making the eyes independent of the scaling factor). I'll try to sort out a new release for ctan tomorrow (getting late here on this site of the big pond :) ).

**Comment by cfroccajr** [comment]
Awesome thanks!!!!

**Comment by samcarter** [comment]
The wolf is its way to ctan https://ctan.org/incoming

Thanks again for contributing the cute wolf!
