### ISSUE TITLE
Wrong place of page number

### ISSUE THREAD

**Issue by TomBener** [samcarter/tikzlings#9]
Hello, 

I run a `.tex` file written by me 2 weeks ago with tikzlings package today (14th, July), while the place of page number was wrong, as contrary, which was good 2 weeks ago. My TeX distribution is MacTeX 2019, and the file was ran with XeLaTeX typesetting engine.

Here is the MWE:

```
\documentclass[12pt, a4paper]{article}

\linespread{1.3}
\usepackage[margin=2.5cm]{geometry}
\usepackage{microtype, setspace}
\usepackage[T1]{fontenc}
\usepackage{mathptmx}
\usepackage{lipsum}

\usepackage{fancyhdr}
\pagestyle{fancy}
\renewcommand\headrulewidth{0pt}

\usepackage{tikzlings}
\cfoot{
  \begin{tikzpicture}[scale=0.5] 
      \tikzling[signpost={\thepage}]
  \end{tikzpicture}
}
\setlength{\footskip}{1.5cm}

\begin{document}
\lipsum[1-12]
\end{document}
```

And the output of PDF was as follows:

![](https://i.loli.net/2019/07/14/5d2aea74aa07085808.png)

It's easy to see the number of page 2 is not at the center of the flag, as well as every page number.

And the previous output of PDF's page number was the same as the tikzlings-doc, which looked like the screenshot below:

![](https://i.loli.net/2019/07/14/5d2aebcb5c19a39412.png)

I'v no idea why. The difference between them really confused me. It would be grateful if you could help me handle the issue.

Thank you!

**Comment by samcarter** [comment]
Thanks for reporting this problem!

The change of behaviour seems to be caused by this commit to pgf/tikz:

https://github.com/pgf-tikz/pgf/commit/d0f66607f379dadd6d5a435fa86567fe36cfb842

I have no idea if the shift of the page numbers is intended, I will try to find out.

**Comment by samcarter** [comment]
related issue: https://github.com/pgf-tikz/pgf/issues/709

**Comment by samcarter** [comment]
seems to be a bug in pgf https://github.com/pgf-tikz/pgf/issues/708
